# Site settings
title: Karthik Nandula
description: >-
  Think Different.
lang: en-UK
timezone: Europe/London
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/kvnandula04/kvnandula04.github.io
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Karthik Nandula
  bio: >-
    Welcome to my 'Mind Garden'! Have a look around.
  username: kvnandula04
  email: kvnandula04@gmail.com
  avatar: /assets/img/avatar.jpeg

# Url settings
url: "https://wiki.karsidonline.com"
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-postfiles
